name: E2E Test
on:
  schedule:
  # Hammer the backend by running this every 5mins 😈
    - cron: '*/5 * * * *'
  push:

jobs:
    integration:
        name: Integration Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  cache: 'yarn'
                  node-version: 16.14.2

            - name: Cache playwright binaries
              uses: actions/cache@v2
              id: playwright-cache
              with:
                  path: |
                      ~/.cache/ms-playwright
                  key: cache-playwright-linux-1.21.0

            - name: Install dependencies
              run: yarn install --immutable
              env:
                  YARN_ENABLE_IMMUTABLE_INSTALLS: false

            - name: Build packages
              run: yarn build

            - name: Install Playwright
              if: steps.playwright-cache.outputs.cache-hit != 'true'
              run: npx playwright install --with-deps && npx @replayio/playwright install

            - name: Integration Tests
              run: yarn workspace integration tests:replay

            - name: List replays
              run: npx @replayio/replay ls
              if: ${{ always() }}

            - name: Upload Replays
              uses: replayio/action-upload@v0.4.3
              if: ${{ always() }}
              with:
                  public: true
                  api-key: rwk_rU0zn3HTo6ln30JdS6QCVJNcuxld0nyWNsN1RhKgt3y