name: E2E Test
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    outputs:
      recordDuration: ${{steps.end.outputs.recordDuration}}
      uploadDuration: ${{steps.end.outputs.uploadDuration}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16.14.2

      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Build packages
        run: yarn build

      - name: Install Playwright
        run: npx playwright install --with-deps && npx @replayio/playwright install
        
      - name: Set test start
        if: always()
        id: recordStart
        run: echo "time=`date +%s`" >> $GITHUB_OUTPUT

      - name: Integration Tests
        run: yarn workspace integration tests:replay
        env:
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}

      - name: Set upload start
        if: always()
        id: uploadStart
        run: echo "time=`date +%s`" >> $GITHUB_OUTPUT

      - name: Upload Replays
        uses: replayio/action-upload@v0.4.3
        if: ${{ always() }}
        with:
          public: true
          api-key: rwk_E7cBJRWfqVj1PedMiDiBdvfBcVTTxyPRAsQFuHwDv24

      - name: Set duration in output
        id: end
        if: always()
        run: | 
          echo "recordDuration=$((${{ steps.uploadStart.outputs.time }} - ${{ steps.recordStart.outputs.time }}))" >> $GITHUB_OUTPUT
          echo "uploadDuration=$((`date +%s` - ${{ steps.uploadStart.outputs.time }}))" >> $GITHUB_OUTPUT

  no-record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16.14.2

      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Build packages
        run: yarn build

      - name: Install Playwright
        run: npx playwright install --with-deps && npx @replayio/playwright install

      - name: Integration Tests
        run: yarn workspace integration tests:replay
        env:
          RECORD_REPLAY_NO_RECORD: 1
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
  original:
    runs-on: ubuntu-latest
    outputs:
     duration: ${{steps.end.outputs.duration}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16.14.2

      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Build packages
        run: yarn build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Set test start
        if: always()
        id: start
        run: echo "time=`date +%s`" >> $GITHUB_OUTPUT

      - name: Integration Tests
        run: yarn workspace integration tests
        env:
          RECORD_REPLAY_NO_RECORD: 1
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
      - name: Set duration in output
        if: always()
        id: end
        run: echo "duration=$((`date +%s` - ${{ steps.start.outputs.time }}))" >> $GITHUB_OUTPUT

  upload-benchmarks:
    name: Upload benchmarks
    runs-on: ubuntu-latest
    needs: [record, original]
    if: always()
    steps:
      - run: |
          echo "Original Duration: ${{ needs.original.outputs.duration }}"
          echo "Record Duration: ${{ needs.record.outputs.recordDuration }}"
          echo "Upload Duration: ${{ needs.record.outputs.uploadDuration }}"
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://telemetry.replay.io"
          configuration: '{ "method": "POST", "body": {"event": "Webhook", "source": "metrics", "name": "action-finished", "project": "houdini", "originalDuration": "${{ needs.original.outputs.duration }}", "recordDuration": "${{ needs.record.outputs.recordDuration }}", "uploadDuration": "${{ needs.record.outputs.uploadDuration }}"} }'

